<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'sextans_api' => [[], ['_controller' => 'App\\Controller\\SextansApiController::index'], [], [['text', '/']], [], []],
    'show_contacts_api' => [[], ['_controller' => 'App\\Controller\\SextansApiController::ShowAllContactsAction'], [], [['text', '/api/v1/show-contacts/']], [], []],
    'save_contact_api' => [[], ['_controller' => 'App\\Controller\\SextansApiController::saveSingleMessageAction'], [], [['text', '/api/v1/save-contact/']], [], []],
];
