<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLkbxadR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLkbxadR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLkbxadR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLkbxadR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLkbxadR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LkbxadR',
    'container.build_id' => '69bc5bfc',
    'container.build_time' => 1580847826,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLkbxadR');
